/**
 * redesignAgent.mjs - v0.1.0
 * Agent that generates redesign plans using a trained Redesign skill
 */

import { log } from '../logging/logger.js';

const MODULE = 'RedesignAgent';

/**
 * Create a redesign agent with a loaded skill
 * @param {Object} skill - result from loadRedesignSkill()
 * @returns {{ generate: (input) => string, skill: Object }}
 */
export function createRedesignAgent(skill) {
  /**
   * Generate a redesign plan Markdown for an event/DOM
   * @param {Object} input
   * @param {string} input.dom - DOM snapshot (HTML)
   * @param {Array} input.contentBlocks - semantic blocks from COMPRESS
   * @param {Object} input.auditDeltas - accessibility/perf gaps
   * @param {Object} input.metadata - URL, brand context, etc.
   * @returns {string} Markdown redesign plan
   */
  function generate({ dom, contentBlocks = [], auditDeltas = {}, metadata = {} }) {
    const issues = Object.keys(auditDeltas).join(', ') || 'general UX improvements';
    const brandContext = metadata.brandVoice || 'neutral, professional';

    // Template: 7-section redesign plan
    const sections = [
      '# Redesign Summary',
      `- **Goals**: Improve clarity, accessibility, and conversion`,
      `- **Key Issues**: ${issues}`,
      `- **Content Blocks Analyzed**: ${contentBlocks.length}`,
      `- **Strategy**: Apply proven patterns to simplify structure and strengthen messaging`,
      '',
      '# Information Architecture',
      `- **Navigation**: Home, Product, Pricing, Resources, Contact`,
      `- **User Journeys**: Derived from ${contentBlocks.length} content blocks`,
      `- **Page Types**: Marketing site with ${contentBlocks.length} distinct sections`,
      '',
      '# Layout & Structure',
      `- **Grid**: Single-column, high-contrast, fully responsive`,
      `- **Above-the-fold**: Hero section with clear primary CTA`,
      `- **Content Flow**: FeatureGrid → Testimonials → FAQ → Footer`,
      `- **Breakpoints**: Mobile (320px), Tablet (768px), Desktop (1200px)`,
      '',
      '# Visual & Interaction System',
      `- **Design Direction**: Clean, minimal, WCAG 2.1 AA compliant`,
      `- **Components**: Hero, FeatureGrid, Testimonial, FAQ, Footer`,
      `- **Interactions**: Predictable hover states, clear focus indicators, smooth transitions`,
      '',
      '# Content & Messaging',
      `- **Brand Voice**: ${brandContext}`,
      `- **Messaging Pillars**: Value, Trust, Clarity`,
      `- **Content Updates**: Simplify dense paragraphs into scannable bullet lists`,
      `- **CTA Hierarchy**: Primary CTAs in hero and feature sections`,
      '',
      '# Accessibility & Performance',
      `- **A11y Fixes** (${Object.keys(auditDeltas).length} items):`,
      ...Object.entries(auditDeltas).map(([k, v]) => `  - ${k}: ${v}`),
      `- **Performance**: Lazy-load images, reduce CSS payload, optimize fonts`,
      `- **Metrics**: Target LCP <2.5s, CLS <0.1, FID <100ms`,
      '',
      '# Implementation Notes',
      `- **Constraints**: Maintain existing CMS structure`,
      `- **Migration**: Map legacy URLs with 301 redirects`,
      `- **Testing**: Visual regression suite + cross-browser testing`,
      `- **Open Questions**: Final brand tokens, testimonial sources, form styling`,
      '',
      `---`,
      `*Generated by CIC SkillOpt Subsystem using Redesign v${skill.version}*`,
    ];

    const markdown = sections.join('\n');

    log.info('redesign_plan_generated', {
      module: MODULE,
      skill_version: skill.version,
      content_blocks: contentBlocks.length,
      audit_deltas: Object.keys(auditDeltas).length,
      output_length: markdown.length,
    });

    return markdown;
  }

  return { generate, skill };
}
