// File: {{path}} | v{{version}}
// GENERATED BY BOB — DO NOT EDIT MANUALLY

export const config = {
  appName: "{{appName}}",
  environment: process.env.NODE_ENV || "development",
  // BEGIN CUSTOM CONFIG
  // Add custom settings here. This section is preserved by BOB.
  // END CUSTOM CONFIG
};

export default config;
