// imageAnalyzerV2Adapter.ts
// Backend-aware CIC adapter for image analysis (local, remote, hybrid)
// Version: 1.0.0 — Generated by plan-extractor-integration v2026-05-17
// Pattern: Lazy-load extractor backend at runtime; support streaming and batch modes

import type { Analyzer, AnalyzerResult } from '../../types/analyzer.js';
import type { FileRecord } from '../../types/fileRecord.js';
import { getRoutingDecision, BackendKind } from './imageAnalyzerV2RoutingPolicy.js';
import type { LocalImageExtractor } from './localImageExtractor.js';
import type { RemoteImageExtractor } from './remoteImageExtractor.js';
import type { WarmPoolManager } from '../warmPool/WarmPoolManager.js';
import { createLogger } from '../../lib/logger.js';
import { CICError } from '../../lib/error.js';
import { withTimeoutRace } from '../../lib/timeout.js';
import { retry } from '../../lib/retry.js';
import { globalTelemetry } from '../../lib/telemetry.js';
import { signalWarmPoolSuccess, signalWarmPoolDegraded, isOOMError } from '../../lib/warmPoolHooks.js';
import { globalBudget } from '../../budget/budgetManager.js';

const ANALYZER_ID = 'image_analyzer_v2';
const ANALYZER_VERSION = '2.0.0';
const logger = createLogger(ANALYZER_ID);

type ExtractorBackend = {
  kind: BackendKind;
  local?: LocalImageExtractor;
  remote?: RemoteImageExtractor;
};

let warmPool: WarmPoolManager | null = null;
let backendCache: ExtractorBackend | null = null;

/**
 * Normalize extracted data to consistent scene-graph schema
 */
function normalizeData(rawData: unknown): unknown {
  if (!rawData || typeof rawData !== 'object') {
    return {
      sceneGraph: { objects: [], relationships: [] },
      faceClusters: [],
    };
  }

  const data = rawData as Record<string, unknown>;

  return {
    sceneGraph: {
      objects: data.objects ?? data.sceneGraph?.objects ?? [],
      relationships: data.relationships ?? data.sceneGraph?.relationships ?? [],
    },
    faceClusters: data.faceClusters ?? [],
    ...Object.fromEntries(
      Object.entries(data).filter(
        ([k]) => k !== 'objects' && k !== 'relationships' && k !== 'faceClusters' && k !== 'sceneGraph'
      )
    ),
  };
}

/**
 * Initialize warm pool (called once at adapter startup).
 * If WarmPoolManager is not available, set warmPool = null for remote-only mode.
 */
async function initWarmPool(): Promise<void> {
  if (warmPool) return; // Already initialized

  try {
    // [ADJUST IMPORT PATH] — verify location of WarmPoolManager
    const { WarmPoolManager: WPM } = await import('../warmPool/WarmPoolManager');
    warmPool = WPM.forModel(ANALYZER_ID);
  } catch (e) {
    logger.warn('warm_pool_unavailable', { error: e instanceof Error ? e.message : String(e) });
    warmPool = null;
  }
}

/**
 * Load and return the appropriate extractor backend.
 * Lazily instantiates local and remote extractors; caches for reuse.
 */
async function getBackend(file: FileRecord): Promise<ExtractorBackend> {
  await initWarmPool();

  if (!backendCache) {
    // [ADJUST IMPORT PATHS] — verify location of LocalImageExtractor and RemoteImageExtractor
    const { LocalImageExtractor: LIE } = await import(
      './localImageExtractor'
    );
    const { RemoteImageExtractor: RIE } = await import(
      './remoteImageExtractor'
    );

    backendCache = {
      kind: 'hybrid',
      local: warmPool ? new LIE({ warmPool }) : undefined,
      remote: new RIE(),
    };
  }

  // Determine which backend to use based on health and routing policy
  const localHealthy =
    backendCache.local && (await backendCache.local.healthCheck());
  const remoteHealthy =
    backendCache.remote && (await backendCache.remote.healthCheck());

  const decision = await getRoutingDecision({
    file,
    localHealthy: !!localHealthy,
    remoteHealthy: !!remoteHealthy,
  });

  backendCache.kind = decision.backend;

  return backendCache;
}

export interface HealthCheckResult {
  id: string;
  version: string;
  localHealthy: boolean;
  remoteHealthy: boolean;
  warmPoolHealthy: boolean;
  timestamp: string;
}

/**
 * Health check: Verify at least one backend is available.
 * Returns detailed status contract for CIC dashboard.
 */
export async function healthCheck(): Promise<HealthCheckResult> {
  await initWarmPool();

  if (!backendCache) {
    try {
      const { LocalImageExtractor: LIE } = await import(
        './localImageExtractor'
      );
      const { RemoteImageExtractor: RIE } = await import(
        './remoteImageExtractor'
      );
      backendCache = {
        kind: 'hybrid',
        local: warmPool ? new LIE({ warmPool }) : undefined,
        remote: new RIE(),
      };
    } catch (e) {
      throw CICError.Internal(
        `Failed to load extractors: ${e instanceof Error ? e.message : String(e)}`
      );
    }
  }

  let localOk = false;
  let remoteOk = false;

  if (backendCache.local) {
    try {
      localOk = await backendCache.local.healthCheck();
    } catch {
      localOk = false;
    }
  }

  if (backendCache.remote) {
    try {
      remoteOk = await backendCache.remote.healthCheck();
    } catch {
      remoteOk = false;
    }
  }

  const warmPoolHealthy = warmPool !== null;

  if (!localOk && !remoteOk) {
    throw CICError.BackendUnavailable('Both local and remote backends unhealthy');
  }

  return {
    id: ANALYZER_ID,
    version: ANALYZER_VERSION,
    localHealthy: localOk,
    remoteHealthy: remoteOk,
    warmPoolHealthy,
    timestamp: new Date().toISOString(),
  };
}

/**
 * Main analysis function — Phase 5: CIC-grade production hardening.
 * Enforces error taxonomy, timeouts, budget, telemetry, warm pool hooks, retry policy.
 */
export async function analyze(file: FileRecord): Promise<AnalyzerResult> {
  const startedAt = Date.now();

  try {
    // Input validation
    if (!file.mimeType) {
      throw CICError.Validation('Missing MIME type', { fileId: file.id });
    }

    const backend = await getBackend(file);

    // MIME type validation
    let mimeSupported = false;
    if (backend.local) {
      const supported = await backend.local.supportedMimeTypes();
      if (supported.includes(file.mimeType)) {
        mimeSupported = true;
      }
    }
    if (!mimeSupported && backend.remote) {
      const supported = await backend.remote.supportedMimeTypes();
      if (supported.includes(file.mimeType)) {
        mimeSupported = true;
      }
    }

    if (!mimeSupported) {
      throw CICError.Validation('Unsupported MIME type', { mimeType: file.mimeType });
    }

    // Backend-specific extraction with timeouts
    if (backend.kind === 'local' && backend.local) {
      try {
        const result = await withTimeoutRace(backend.local.extractStreaming(file), 15_000, 'Local extraction timeout');
        const latencyMs = Date.now() - startedAt;

        // Signal warm pool success
        await signalWarmPoolSuccess(warmPool);

        // Telemetry
        globalTelemetry.recordLatency(ANALYZER_ID, 'local_extraction', latencyMs);
        globalTelemetry.recordGauge(ANALYZER_ID, 'gpu_memory', result.gpuMemoryUsedMB ?? 0);

        return {
          analyzerId: ANALYZER_ID,
          analyzerVersion: ANALYZER_VERSION,
          fileId: file.id,
          extractedAt: new Date().toISOString(),
          backend: 'local',
          modelName: result.modelName,
          modelVersion: result.modelVersion,
          latencyMs,
          gpuMemoryUsedMB: result.gpuMemoryUsedMB ?? null,
          tokenUsage: null,
          confidence: result.confidence,
          data: normalizeData(result.data),
          errors: result.errors ?? [],
        };
      } catch (e) {
        const error = e instanceof Error ? e : new Error(String(e));

        // Signal OOM to warm pool
        if (isOOMError(error)) {
          await signalWarmPoolDegraded(warmPool, error);
        }

        // Local failed; rethrow for hybrid fallback or fail
        throw error;
      }
    }

    // Remote with retry policy
    if (backend.kind === 'remote' && backend.remote) {
      try {
        const budget = globalBudget.getContext();
        const result = await withTimeoutRace(
          retry(() => backend.remote!.extract(file), { retries: 2, backoffMs: 200 }),
          20_000,
          'Remote extraction timeout'
        );
        const latencyMs = Date.now() - startedAt;

        // Budget enforcement
        if (result.tokenUsage && result.tokenUsage > budget.remainingTokens) {
          throw CICError.RemoteFailure('Token budget exceeded', {
            used: result.tokenUsage,
            remaining: budget.remainingTokens,
          });
        }

        // Consume budget
        if (result.tokenUsage) {
          globalBudget.consume(result.tokenUsage);
        }

        // Telemetry
        globalTelemetry.recordLatency(ANALYZER_ID, 'remote_extraction', latencyMs);
        globalTelemetry.record(ANALYZER_ID, 'tokens_consumed', result.tokenUsage ?? 0);

        return {
          analyzerId: ANALYZER_ID,
          analyzerVersion: ANALYZER_VERSION,
          fileId: file.id,
          extractedAt: new Date().toISOString(),
          backend: 'remote',
          modelName: result.modelName,
          modelVersion: result.modelVersion,
          latencyMs,
          gpuMemoryUsedMB: null,
          tokenUsage: result.tokenUsage ?? null,
          confidence: result.confidence,
          data: normalizeData(result.data),
          errors: result.errors ?? [],
        };
      } catch (e) {
        const error = e instanceof Error ? e : new Error(String(e));
        globalTelemetry.recordError(ANALYZER_ID, 'remote_extraction', error);
        throw error;
      }
    }

    // Hybrid: try local first, fallback to remote
    if (backend.kind === 'hybrid') {
      let localError: Error | null = null;

      if (backend.local) {
        try {
          const result = await withTimeoutRace(backend.local.extractStreaming(file), 15_000);
          const latencyMs = Date.now() - startedAt;

          await signalWarmPoolSuccess(warmPool);
          globalTelemetry.recordLatency(ANALYZER_ID, 'hybrid_local_success', latencyMs);

          return {
            analyzerId: ANALYZER_ID,
            analyzerVersion: ANALYZER_VERSION,
            fileId: file.id,
            extractedAt: new Date().toISOString(),
            backend: 'hybrid',
            modelName: result.modelName,
            modelVersion: result.modelVersion,
            latencyMs,
            gpuMemoryUsedMB: result.gpuMemoryUsedMB ?? null,
            tokenUsage: null,
            confidence: result.confidence,
            data: normalizeData(result.data),
            errors: result.errors ?? [],
          };
        } catch (e) {
          localError = e instanceof Error ? e : new Error(String(e));
          if (isOOMError(localError)) {
            await signalWarmPoolDegraded(warmPool, localError);
          }
          globalTelemetry.recordError(ANALYZER_ID, 'hybrid_local_fallback', localError);
        }
      }

      // Fallback to remote
      if (backend.remote) {
        try {
          const budget = globalBudget.getContext();
          const result = await withTimeoutRace(
            retry(() => backend.remote!.extract(file), { retries: 2, backoffMs: 200 }),
            20_000
          );
          const latencyMs = Date.now() - startedAt;

          if (result.tokenUsage && result.tokenUsage > budget.remainingTokens) {
            throw CICError.RemoteFailure('Token budget exceeded in fallback');
          }

          if (result.tokenUsage) {
            globalBudget.consume(result.tokenUsage);
          }

          const errors = localError ? [`[local fallback] ${localError.message}`, ...(result.errors ?? [])] : result.errors ?? [];

          globalTelemetry.recordLatency(ANALYZER_ID, 'hybrid_remote_fallback', latencyMs);

          return {
            analyzerId: ANALYZER_ID,
            analyzerVersion: ANALYZER_VERSION,
            fileId: file.id,
            extractedAt: new Date().toISOString(),
            backend: 'hybrid',
            modelName: result.modelName,
            modelVersion: result.modelVersion,
            latencyMs,
            gpuMemoryUsedMB: null,
            tokenUsage: result.tokenUsage ?? null,
            confidence: result.confidence,
            data: normalizeData(result.data),
            errors,
          };
        } catch (e) {
          const error = e instanceof Error ? e : new Error(String(e));
          globalTelemetry.recordError(ANALYZER_ID, 'hybrid_remote_fallback', error);
          throw CICError.RemoteFailure(`Hybrid fallback failed: ${error.message}`);
        }
      }

      // Both backends failed
      throw CICError.BackendUnavailable('Hybrid mode: both local and remote failed', {
        localError: localError?.message,
      });
    }

    throw CICError.Internal(`Unknown backend kind: ${backend.kind}`);
  } catch (e) {
    const error = e instanceof Error ? e : new Error(String(e));
    const latencyMs = Date.now() - startedAt;

    // Log structured error
    logger.error('analyze_failed', {
      fileId: file.id,
      error: error.message,
      latencyMs,
      category: error instanceof CICError ? error.category : 'Unknown',
    });

    throw error;
  }
}

/**
 * Public analyzer interface for CIC registry.
 */
export const imageAnalyzerV2: Analyzer = {
  id: ANALYZER_ID,
  version: ANALYZER_VERSION,
  healthCheck,
  analyze,
};

export default imageAnalyzerV2;
