// imageAnalyzerV2Adapter.ts
// Backend-aware CIC adapter for image analysis (local, remote, hybrid)
// Version: 1.0.0 — Generated by plan-extractor-integration v2026-05-17
// Pattern: Lazy-load extractor backend at runtime; support streaming and batch modes

import type { Analyzer, AnalyzerResult } from '../../types/analyzer.js';
import type { FileRecord } from '../../types/fileRecord.js';
import { getRoutingDecision, BackendKind } from './imageAnalyzerV2RoutingPolicy.js';
import type { LocalImageExtractor } from './localImageExtractor.js';
import type { RemoteImageExtractor } from './remoteImageExtractor.js';
import type { WarmPoolManager } from '../warmPool/WarmPoolManager.js';
import { createLogger } from '../../lib/logger.js';

const ANALYZER_ID = 'image_analyzer_v2';
const ANALYZER_VERSION = '2.0.0';
const logger = createLogger(ANALYZER_ID);

type ExtractorBackend = {
  kind: BackendKind;
  local?: LocalImageExtractor;
  remote?: RemoteImageExtractor;
};

let warmPool: WarmPoolManager | null = null;
let backendCache: ExtractorBackend | null = null;

/**
 * Normalize extracted data to consistent scene-graph schema
 */
function normalizeData(rawData: unknown): unknown {
  if (!rawData || typeof rawData !== 'object') {
    return {
      sceneGraph: { objects: [], relationships: [] },
      faceClusters: [],
    };
  }

  const data = rawData as Record<string, unknown>;

  return {
    sceneGraph: {
      objects: data.objects ?? data.sceneGraph?.objects ?? [],
      relationships: data.relationships ?? data.sceneGraph?.relationships ?? [],
    },
    faceClusters: data.faceClusters ?? [],
    ...Object.fromEntries(
      Object.entries(data).filter(
        ([k]) => k !== 'objects' && k !== 'relationships' && k !== 'faceClusters' && k !== 'sceneGraph'
      )
    ),
  };
}

/**
 * Initialize warm pool (called once at adapter startup).
 * If WarmPoolManager is not available, set warmPool = null for remote-only mode.
 */
async function initWarmPool(): Promise<void> {
  if (warmPool) return; // Already initialized

  try {
    // [ADJUST IMPORT PATH] — verify location of WarmPoolManager
    const { WarmPoolManager: WPM } = await import('../warmPool/WarmPoolManager');
    warmPool = WPM.forModel(ANALYZER_ID);
  } catch (e) {
    logger.warn('warm_pool_unavailable', { error: e instanceof Error ? e.message : String(e) });
    warmPool = null;
  }
}

/**
 * Load and return the appropriate extractor backend.
 * Lazily instantiates local and remote extractors; caches for reuse.
 */
async function getBackend(file: FileRecord): Promise<ExtractorBackend> {
  await initWarmPool();

  if (!backendCache) {
    // [ADJUST IMPORT PATHS] — verify location of LocalImageExtractor and RemoteImageExtractor
    const { LocalImageExtractor: LIE } = await import(
      './localImageExtractor'
    );
    const { RemoteImageExtractor: RIE } = await import(
      './remoteImageExtractor'
    );

    backendCache = {
      kind: 'hybrid',
      local: warmPool ? new LIE({ warmPool }) : undefined,
      remote: new RIE(),
    };
  }

  // Determine which backend to use based on health and routing policy
  const localHealthy =
    backendCache.local && (await backendCache.local.healthCheck());
  const remoteHealthy =
    backendCache.remote && (await backendCache.remote.healthCheck());

  const decision = await getRoutingDecision({
    file,
    localHealthy: !!localHealthy,
    remoteHealthy: !!remoteHealthy,
  });

  backendCache.kind = decision.backend;

  return backendCache;
}

/**
 * Health check: Verify at least one backend is available.
 * Throws if both backends are unhealthy.
 */
export async function healthCheck(): Promise<void> {
  await initWarmPool();

  if (!backendCache) {
    try {
      const { LocalImageExtractor: LIE } = await import(
        './localImageExtractor'
      );
      const { RemoteImageExtractor: RIE } = await import(
        './remoteImageExtractor'
      );
      backendCache = {
        kind: 'hybrid',
        local: warmPool ? new LIE({ warmPool }) : undefined,
        remote: new RIE(),
      };
    } catch (e) {
      throw new Error(
        `[${ANALYZER_ID}] Failed to load extractors during healthCheck: ${e instanceof Error ? e.message : String(e)}`
      );
    }
  }

  let localOk = false;
  let remoteOk = false;

  if (backendCache.local) {
    try {
      localOk = await backendCache.local.healthCheck();
    } catch {
      localOk = false;
    }
  }

  if (backendCache.remote) {
    try {
      remoteOk = await backendCache.remote.healthCheck();
    } catch {
      remoteOk = false;
    }
  }

  if (!localOk && !remoteOk) {
    throw new Error(
      `[${ANALYZER_ID}] healthCheck failed: both local and remote backends unhealthy`
    );
  }
}

/**
 * Main analysis function.
 * Selects backend (local/remote/hybrid), validates MIME type, and extracts image metadata.
 *
 * Returns deterministic AnalyzerResult with backend metadata, latency, and error info.
 */
export async function analyze(file: FileRecord): Promise<AnalyzerResult> {
  const backend = await getBackend(file);

  // MIME type validation
  let mimeSupported = false;
  if (backend.local) {
    const supported = await backend.local.supportedMimeTypes();
    if (supported.includes(file.mimeType)) {
      mimeSupported = true;
    }
  }
  if (!mimeSupported && backend.remote) {
    const supported = await backend.remote.supportedMimeTypes();
    if (supported.includes(file.mimeType)) {
      mimeSupported = true;
    }
  }

  if (!mimeSupported) {
    throw new Error(
      `[${ANALYZER_ID}] unsupported MIME type: ${file.mimeType}`
    );
  }

  const startedAt = Date.now();

  // Backend-specific extraction
  if (backend.kind === 'local' && backend.local) {
    try {
      const result = await backend.local.extractStreaming(file);
      const latencyMs = Date.now() - startedAt;

      return {
        analyzerId: ANALYZER_ID,
        analyzerVersion: ANALYZER_VERSION,
        fileId: file.id,
        extractedAt: new Date().toISOString(),
        backend: 'local',
        modelName: result.modelName,
        modelVersion: result.modelVersion,
        latencyMs,
        gpuMemoryUsedMB: result.gpuMemoryUsedMB ?? null,
        tokenUsage: null,
        confidence: result.confidence,
        data: normalizeData(result.data),
        errors: result.errors ?? [],
      };
    } catch (e) {
      // Local failed; rethrow for now (hybrid mode handles fallback)
      throw e;
    }
  }

  if (backend.kind === 'remote' && backend.remote) {
    const result = await backend.remote.extract(file);
    const latencyMs = Date.now() - startedAt;

    return {
      analyzerId: ANALYZER_ID,
      analyzerVersion: ANALYZER_VERSION,
      fileId: file.id,
      extractedAt: new Date().toISOString(),
      backend: 'remote',
      modelName: result.modelName,
      modelVersion: result.modelVersion,
      latencyMs,
      gpuMemoryUsedMB: null,
      tokenUsage: result.tokenUsage ?? null,
      confidence: result.confidence,
      data: normalizeData(result.data),
      errors: result.errors ?? [],
    };
  }

  // Hybrid: try local first, fallback to remote on error
  if (backend.kind === 'hybrid') {
    let localError: Error | null = null;

    if (backend.local) {
      try {
        const result = await backend.local.extractStreaming(file);
        const latencyMs = Date.now() - startedAt;

        return {
          analyzerId: ANALYZER_ID,
          analyzerVersion: ANALYZER_VERSION,
          fileId: file.id,
          extractedAt: new Date().toISOString(),
          backend: 'hybrid',
          modelName: result.modelName,
          modelVersion: result.modelVersion,
          latencyMs,
          gpuMemoryUsedMB: result.gpuMemoryUsedMB ?? null,
          tokenUsage: null,
          confidence: result.confidence,
          data: normalizeData(result.data),
          errors: result.errors ?? [],
        };
      } catch (e) {
        localError = e instanceof Error ? e : new Error(String(e));
      }
    }

    // Local failed; use remote fallback
    if (backend.remote) {
      const result = await backend.remote.extract(file);
      const latencyMs = Date.now() - startedAt;

      const errors = localError
        ? [
            `[local fallback] ${localError.message}`,
            ...(result.errors ?? []),
          ]
        : result.errors ?? [];

      return {
        analyzerId: ANALYZER_ID,
        analyzerVersion: ANALYZER_VERSION,
        fileId: file.id,
        extractedAt: new Date().toISOString(),
        backend: 'hybrid',
        modelName: result.modelName,
        modelVersion: result.modelVersion,
        latencyMs,
        gpuMemoryUsedMB: null,
        tokenUsage: result.tokenUsage ?? null,
        confidence: result.confidence,
        data: normalizeData(result.data),
        errors,
      };
    }

    // Both failed
    throw new Error(
      `[${ANALYZER_ID}] hybrid mode: local failed and remote unavailable`
    );
  }

  // Should never reach here
  throw new Error(`[${ANALYZER_ID}] unknown backend kind: ${backend.kind}`);
}

/**
 * Public analyzer interface for CIC registry.
 */
export const imageAnalyzerV2: Analyzer = {
  id: ANALYZER_ID,
  version: ANALYZER_VERSION,
  healthCheck,
  analyze,
};

export default imageAnalyzerV2;
