/**
 * js/efficacy-panel.js
 * @version 1.0.0
 * @date 2026-05-21
 *
 * MAS Efficacy Lab Dashboard Panel.
 * Visualizes the value generated by MAS interventions.
 */

const EfficacyPanel = (() => {
  'use strict';

  let _container = null;

  function init(containerId) {
    _container = document.getElementById(containerId);
    if (!_container) return;

    _renderSkeleton();
  }

  function _renderSkeleton() {
    _container.innerHTML = `
      <div class="mas-header">
        <h2>MAS Efficacy Lab (Provable Value)</h2>
        <div class="mas-stat"><span class="mas-stat-label" style="font-size:10px;">Delta Analysis Engine</span></div>
      </div>

      <div class="efficacy-grid">
        <div class="efficacy-card">
          <div class="efficacy-value" id="eff-failures-avoided">0</div>
          <div class="efficacy-label">Failures Avoided</div>
        </div>
        <div class="efficacy-card">
          <div class="efficacy-value" id="eff-instability-prevented">0m</div>
          <div class="efficacy-label">Instability Prevented</div>
        </div>
        <div class="efficacy-card">
          <div class="efficacy-value" id="eff-net-positive">0%</div>
          <div class="efficacy-label">Net-Positive Rate</div>
        </div>
        <div class="efficacy-card">
          <div class="efficacy-value" id="eff-interventions">0</div>
          <div class="efficacy-label">Total Interventions</div>
        </div>
      </div>

      <div class="replay-lab">
        <h3>Incident Replay Console</h3>
        <div id="replay-console-log" class="replay-log">
          <div class="empty-msg">No active replays. Lab idle.</div>
        </div>
      </div>

      <style>
        .efficacy-grid {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 16px;
          margin-bottom: 20px;
        }
        .efficacy-card {
          background: #0d1117;
          border: 1px solid #30363d;
          border-radius: 6px;
          padding: 16px;
          text-align: center;
          border-bottom: 3px solid var(--online);
        }
        .efficacy-value {
          font-family: 'JetBrains Mono', monospace;
          font-size: 24px;
          font-weight: bold;
          color: var(--accent);
          text-shadow: 0 0 10px rgba(56, 139, 253, 0.2);
        }
        .efficacy-label {
          font-size: 9px;
          color: #8b949e;
          text-transform: uppercase;
          margin-top: 4px;
          letter-spacing: 0.1em;
        }

        .replay-lab h3 {
          font-size: 10px;
          color: #8b949e;
          text-transform: uppercase;
          margin-bottom: 12px;
          border-bottom: 1px solid #30363d;
          padding-bottom: 4px;
        }
        .replay-log {
          height: 100px;
          background: #0b0e14;
          border: 1px solid #30363d;
          border-radius: 6px;
          padding: 8px;
          font-family: 'JetBrains Mono', monospace;
          font-size: 10px;
          overflow-y: auto;
        }
        .replay-entry {
          padding: 4px 0;
          border-bottom: 1px solid rgba(48, 54, 61, 0.5);
          color: #c9d1d9;
        }
        .replay-ts { color: #484f58; margin-right: 8px; }
        .replay-gain { color: var(--online); font-weight: bold; }
      </style>
    `;
  }

  function update(records) {
    if (!_container) return;

    const stats = MASEfficacy.analyze(records);
    
    document.getElementById('eff-failures-avoided').textContent = stats.failuresAvoided;
    document.getElementById('eff-instability-prevented').textContent = stats.instabilityPrevented + 'm';
    document.getElementById('eff-net-positive').textContent = stats.netPositiveRate + '%';
    document.getElementById('eff-interventions').textContent = stats.interventions;

    _updateReplayLog(records);
  }

  function _updateReplayLog(records) {
    const log = document.getElementById('replay-console-log');
    if (!records.length) return;

    const html = records.slice(0, 10).map(r => {
      const ts = new Date(r.timestamp).toLocaleTimeString([], { hour12: false });
      const gain = r.counterfactuals.noMitigation.projectedFailures - r.counterfactuals.withMitigation.projectedFailures;
      return `
        <div class="replay-entry">
          <span class="replay-ts">[${ts}]</span>
          <span>Replay ID: ${r.id} | Result: <span class="replay-gain">${gain > 0 ? '+' + gain + ' failures avoided' : 'stability preserved'}</span></span>
        </div>
      `;
    }).join('');

    log.innerHTML = html;
  }

  return { init, update };
})();

window.EfficacyPanel = EfficacyPanel;
