/**
 * Daily Digest Synthesizer - Transforms collected data into a Markdown brief.
 */

export class DigestSynthesizer {
  /**
   * Synthesizes collected data into a Markdown string.
   * 
   * @param {Object} data Collected data from DigestCollector
   * @returns {string} Markdown digest
   */
  synthesize(data) {
    const { date, memos, tasks, ideas, operatorNotes } = data;

    let md = `# 🗞️ Daily Digest — ${date}\n\n`;

    // 1. Operator Notes
    if (operatorNotes.length > 0) {
      md += `## ⚠️ Operator Notes\n`;
      for (const note of operatorNotes) {
        md += `- ${note.title}\n`;
      }
      md += `\n`;
    }

    // 2. Tasks
    if (tasks.length > 0) {
      md += `## ✅ Tasks\n`;
      // Sort by priority (1 is highest)
      const sortedTasks = [...tasks].sort((a, b) => a.priority - b.priority);
      for (const task of sortedTasks) {
        const priorityStr = `P${task.priority}`;
        const dueStr = task.due ? ` (due: ${task.due})` : '';
        md += `- [${priorityStr}] ${task.title}${dueStr}\n`;
      }
      md += `\n`;
    }

    // 3. Ideas
    if (ideas.length > 0) {
      md += `## 💡 Ideas\n`;
      // Group by cluster
      const clusters = {};
      for (const idea of ideas) {
        if (!clusters[idea.cluster]) clusters[idea.cluster] = [];
        clusters[idea.cluster].push(idea);
      }

      for (const [cluster, clusterIdeas] of Object.entries(clusters)) {
        md += `### ${cluster}\n`;
        for (const idea of clusterIdeas) {
          md += `- ${idea.title}\n`;
        }
      }
      md += `\n`;
    }

    // 4. Memos
    if (memos.length > 0) {
      md += `## 📝 New Memos\n`;
      for (const memo of memos) {
        md += `- ${memo.title}\n`;
      }
      md += `\n`;
    }

    // 5. Cluster Summary
    if (ideas.length > 0) {
      md += `## 📊 Cluster Summary\n`;
      const clusters = {};
      for (const idea of ideas) {
        clusters[idea.cluster] = (clusters[idea.cluster] || 0) + 1;
      }
      for (const [cluster, count] of Object.entries(clusters)) {
        md += `- ${cluster}: ${count} ${count === 1 ? 'idea' : 'ideas'}\n`;
      }
      md += `\n`;
    }

    md += `---\n*Generated by CIC Daily Digest Subsystem*`;

    return md;
  }
}
