// File: bob/tests/bob.test.js | Date: 2026-05-31 | v1.0.0

import { describe, it, expect } from 'vitest';
import { parseMarkdown } from '../core/parser/markdownParser.js';
import { buildDependencyGraph, getAffectedPipelines } from '../core/graph/dependencyGraph.js';
import { mergeCustomBlocks } from '../core/pipelines/generatorHelper.js';
import { runBuild } from '../core/build.js';
import { runRollback } from '../core/audit/historyManager.js';

describe('BOB — Code Generator & System Core Tests', () => {

  // --- Parser Tests ---
  describe('Markdown Parser AST Tokenizer', () => {
    it('should cleanly parse sections and YAML frontmatter', () => {
      const sampleMarkdown = `---
title: "Test Spec"
version: 1.2.3
---
# Main Spec
This is main body text.
## Proposed Changes
#### [NEW] [DataManager.js]
`;
      const ast = parseMarkdown(sampleMarkdown);

      expect(ast.frontmatter.title).toBe('Test Spec');
      expect(ast.frontmatter.version).toBe('1.2.3');
      expect(ast.sections['Main Spec']).toBeDefined();
      expect(ast.sections['Proposed Changes']).toBeDefined();
      expect(ast.sections['Proposed Changes'][0]).toContain('DataManager.js');
    });
  });

  // --- Dependency Graph Tests ---
  describe('Dependency Graph Resolver', () => {
    it('should map spec files to correct generation pipelines', async () => {
      const mockAST = {
        'projects/cic/ingestion/playbooks/baseline.json': {},
        'projects/cic/docs/task.md': {},
        'api/server-routes.md': {}
      };

      const graph = await buildDependencyGraph(mockAST);

      expect(graph['projects/cic/ingestion/playbooks/baseline.json']).toContain('playbooks');
      expect(graph['projects/cic/docs/task.md']).toContain('modules');
      expect(graph['api/server-routes.md']).toContain('routes');

      // Test active diff changes
      const affected = getAffectedPipelines(graph, { changedFile: 'projects/cic/docs/task.md' });
      expect(affected).toContain('modules');
      expect(affected).toContain('tests');
      expect(affected).toContain('docs');
    });
  });

  // --- Safety & Code Ownership block merging ---
  describe('Human Code Preserving Merges', () => {
    it('should retain custom block code between BEGIN/END fences during generation runs', () => {
      const existingHumanFile = `// File: test.js
// GENERATED BY BOB

export class Core {
  constructor() {
    // BEGIN CUSTOM INITIALIZATION
    this.customId = 42;
    console.log("Human code active");
    // END CUSTOM INITIALIZATION
  }
}
`;

      const newlyGeneratedFile = `// File: test.js
// GENERATED BY BOB

export class Core {
  constructor() {
    // BEGIN CUSTOM INITIALIZATION
    // TODO: Add custom initialization logic here. This block is preserved by BOB.
    // END CUSTOM INITIALIZATION
  }
}
`;

      const merged = mergeCustomBlocks(existingHumanFile, newlyGeneratedFile);

      expect(merged).toContain('this.customId = 42;');
      expect(merged).toContain('Human code active');
    });

    it('should retain custom comment block settings in JSON files', () => {
      const existingConfig = `{
  "name": "App",
  /* BEGIN CUSTOM CONFIG */
  "apiKey": "secret-12345",
  "port": 9000
  /* END CUSTOM CONFIG */
}
`;

      const newlyGeneratedConfig = `{
  "name": "App",
  /* BEGIN CUSTOM CONFIG */
  /* END CUSTOM CONFIG */
}
`;

      const merged = mergeCustomBlocks(existingConfig, newlyGeneratedConfig);

      expect(merged).toContain('"apiKey": "secret-12345"');
      expect(merged).toContain('"port": 9000');
    });
  });

  // --- Full Build & Rollback tests ---
  describe('Orchestrated Build and Rollback', () => {
    it('should run full build and log history successfully', async () => {
      const success = await runBuild();
      expect(success).toBe(true);
    });

    it('should execute rollback simulations cleanly', async () => {
      const success = await runRollback('bob-tx-12345');
      expect(success).toBe(true);
    });
  });

});
