/**
 * CIC v3.0 — Error Codes
 * File: cic/core/errors.js | Version: 1.0.0 | Date: 2026-05-15
 */

export const CIC_ERRORS = Object.freeze({
  CORE_UNKNOWN:              'CIC_CORE_UNKNOWN',
  AGENT_NOT_FOUND:           'CIC_AGENT_NOT_FOUND',
  AGENT_INVALID_CONTRACT:    'CIC_AGENT_INVALID_CONTRACT',
  AGENT_EXECUTE_FAILED:      'CIC_AGENT_EXECUTE_FAILED',
  PIPELINE_RUN_FAILED:       'CIC_PIPELINE_RUN_FAILED',
  INGESTION_INVALID_JOB:     'INGESTION_QUEUE_INVALID_JOB',
  INGESTION_UNKNOWN_SOURCE:  'INGESTION_UNKNOWN_SOURCE_TYPE',
  INGESTION_VALIDATE_EMPTY:  'INGESTION_VALIDATE_EMPTY_PAYLOAD',
  HARVESTER_UNKNOWN_TYPE:    'HARVESTER_UNKNOWN_TYPE',
  ORCH_MISSING_NODE_TYPE:    'ORCH_MISSING_NODE_TYPE',
});
